server:
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
  port: 8081

  
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    messages:
      encoding: utf-8
    mvc:
      static-path-pattern: /static/

      view:
        prefix: classpath:/templates/
        suffix: .html
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

# face++ 配置信息
face:
  apiKey: wXOKblCgoWewYZahJRTcOaZwicrgjYnb
  apiSecret: ZatXrQr7o_mt17OZJa1pdrhxcjw3dCa-
